/**
 * PAC-file support for the ChatGPT desktop send-unblock intercept.
 *
 * With `chatgptDesktop.pacFallback` on, the app is launched with
 * `--proxy-pac-url=file://<configDir>/chatgpt-unblock.pac` instead of a resolver rule. The PAC
 * sends chatgpt.com to the entry CONNECT listener (which splices onto the TLS origin listener),
 * and every other host to the system proxy chain captured when the file was written, with
 * DIRECT last. When opencodex stops, the refused CONNECT makes Chromium fall through the chain
 * on its own -- the app keeps working, no restart -- which is the whole point of the fallback.
 *
 * The chain is captured from `scutil --proxy` at generation time, not hard-coded: whether
 * non-chatgpt.com traffic (and, via the system proxy, chatgpt.com's own fallback) still needs
 * the VPN depends on the VPN's mode at the time. TUN mode exposes no system proxy, so the file
 * degrades to DIRECT and Chromium resolves and dials on its own.
 */

import { execFileSync } from "node:child_process";
import { CHATGPT_INTERCEPT_HOST } from "./listener";

export const CHATGPT_UNBLOCK_PAC_FILENAME = "chatgpt-unblock.pac";

export interface SystemProxyChain {
  /** e.g. "PROXY 127.0.0.1:7892; SOCKS5 127.0.0.1:7892" -- no trailing DIRECT. */
  entries: string[];
  /** True when a PAC file is configured system-wide (we cannot know its contents). */
  autoConfig: boolean;
}

interface ScutilValue {
  get(key: string): string | null;
}

function parseScutilOutput(output: string): ScutilValue {
  const map = new Map<string, string>();
  for (const line of output.split("\n")) {
    const match = /^\s*(\S+)\s*=\s*(.*?)\s*$/.exec(line);
    if (match) map.set(match[1]!, match[2]!);
  }
  return { get: key => map.get(key) ?? null };
}

function runScutil(): ScutilValue | null {
  try {
    return parseScutilOutput(execFileSync("scutil", ["--proxy"], { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }));
  } catch {
    return null;
  }
}

/**
 * The system proxy as Chromium sees it in a PAC: HTTPS proxy first (browser traffic is
 * HTTPS), then HTTP, then SOCKS. A system-level PAC file is unobservable from here, so it
 * maps to no entry -- the same loss the resolver-rule mode already accepts.
 */
export function systemProxyChain(scutil: ScutilValue | null = runScutil()): SystemProxyChain {
  if (!scutil) return { entries: [], autoConfig: false };
  const autoConfig = scutil.get("ProxyAutoConfigEnable") === "1";
  const entries: string[] = [];
  const pushProxy = (enabled: string | null, host: string | null, port: string | null) => {
    if (enabled === "1" && host && port && host !== "(null)" && host !== "") entries.push(`PROXY ${host}:${port}`);
  };
  const pushSocks = (enabled: string | null, host: string | null, port: string | null) => {
    if (enabled === "1" && host && port && host !== "(null)" && host !== "") entries.push(`SOCKS5 ${host}:${port}`);
  };
  pushProxy(scutil.get("HTTPSEnable"), scutil.get("HTTPSProxy"), scutil.get("HTTPSPort"));
  pushProxy(scutil.get("HTTPEnable"), scutil.get("HTTPProxy"), scutil.get("HTTPPort"));
  pushSocks(scutil.get("SOCKSEnable"), scutil.get("SOCKSProxy"), scutil.get("SOCKSPort"));
  return { entries, autoConfig };
}

/**
 * The PAC script. For the intercepted host: the entry listener first (the intercept), then the
 * captured system chain, then DIRECT (the fallback). For every other host: the captured system
 * chain then DIRECT, so login/telemetry/subdomains behave as they would without the feature.
 */
export function buildChatgptUnblockPac(entryPort: number, chain: SystemProxyChain): string {
  const chainText = [...chain.entries, "DIRECT"].join("; ");
  return `// Generated by opencodex for the ChatGPT desktop send-unblock fallback.
// Rewritten at every opencodex start; the ChatGPT app must be relaunched to pick up changes.
function FindProxyForURL(url, host) {
  if (host == "${CHATGPT_INTERCEPT_HOST}") return "PROXY 127.0.0.1:${entryPort}; ${chainText}";
  return "${chainText}";
}
`;
}
